### ISSUE TITLE
`Error: Can't set headers after they are sent.` when uploading the same files multiple times

### ISSUE THREAD

**Issue by kittaakos** [richardgirges/express-fileupload#120]
I am trying to upload multiple files to my mock server. The first upload ["works"](
https://github.com/richardgirges/express-fileupload/issues/118#issuecomment-462286087), but when I have another POST request with the same files, I have the following error. What am I doing wrong? Thank you!

Bare minimum of my code:
```js
const fs = require('fs');
const join = require('path').join;
const express = require('express');
const fileupload = require('express-fileupload');

const { port, path, root, silent } = { port: 8080, path: '/upload', root: require('os').tmpdir(), silent: false };
const app = express();
app.use(fileupload());

app.post(path, (req, res) => {
    if (!req.files) {
        return res.status(400).send(`No 'files' were selected for upload.`);
    }
    const keys = Object.keys(req.files);
    if (keys.length === 0) {
        return res.status(400).send(`No 'files' were selected for upload.`);
    }
    for (const key of keys) {
        const files = req.files[key];
        const uploads = Array.isArray(files) ? files : [files];
        for (const upload of uploads) {
            const { name, data } = upload;
            const toPath = join(root, name);
            upload.mv(toPath, uploadErr => {
                if (uploadErr) {
                    return res.status(500).send(`Failed to upload ${name}.`);
                }
                // XXX: It's a hack. https://github.com/richardgirges/express-fileupload/issues/118
                const stream = fs.createWriteStream(toPath, { encoding: 'utf8' });
                stream.once('open', () => {
                    stream.write(data, writeErr => {
                        if (writeErr) {
                            return res.status(500).send(`Failed to write content of ${name}.`);
                        }
                        if (!silent) {
                            console.log(`Successfully uploaded '${name}' to ${toPath}.`)
                        }
                        stream.close();
                    })
                });
            });
        }
    }
    res.status(200).send();
});

app.listen(port, () => {
    console.log(`Server is listening on ${port}...`);
    console.log(`Uploaded files will be under ${root}.`);
});
```

POST:
```
curl -F 'foo.txt=@/Users/akos.kitta/Desktop/foo.txt' -F 'bar.txt=@/Users/akos.kitta/Desktop/bar.txt' http://localhost:8080/upload
```

Logs:
```
Server is listening on 8080...
Uploaded files will be under /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T.
Successfully uploaded 'foo.txt' to /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/foo.txt.
Successfully uploaded 'bar.txt' to /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/bar.txt.
Successfully uploaded 'foo.txt' to /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/foo.txt.
Successfully uploaded 'bar.txt' to /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/bar.txt.
_http_outgoing.js:491
    throw new Error('Can\'t set headers after they are sent.');
    ^

Error: Can't set headers after they are sent.
    at validateHeader (_http_outgoing.js:491:11)
    at ServerResponse.setHeader (_http_outgoing.js:498:3)
    at ServerResponse.header (/Users/akos.kitta/git/something/theia-app/node_modules/express/lib/response.js:767:10)
    at ServerResponse.contentType (/Users/akos.kitta/git/something/theia-app/node_modules/express/lib/response.js:595:15)
    at ServerResponse.send (/Users/akos.kitta/git/something/theia-app/node_modules/express/lib/response.js:145:14)
    at upload.mv.uploadErr (/Users/akos.kitta/git/something/theia-app/mocks/a.js:27:44)
    at error (/Users/akos.kitta/git/something/theia-app/node_modules/express-fileupload/lib/fileFactory.js:35:15)
    at /Users/akos.kitta/git/something/theia-app/node_modules/express-fileupload/lib/fileFactory.js:70:13
    at FSReqWrap.oncomplete (fs.js:135:15)
Akoss-MacBook-Pro:lilly_minds akos.kitta$
```

**Comment by RomanBurunkov** [comment]
The first issue I can see that your code can sent 200 OK and then sent 500 Error if something went wrong during moving files.

**Comment by kittaakos** [comment]
@RomanBurunkov, your remark helped a lot. I was blind. Thank you!
