### ISSUE TITLE
Undeefined

### ISSUE THREAD

**Issue by MeetPing** [richardgirges/express-fileupload#159]
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at /home/samuel/Asiakirjat/Catvids/node.js:16:16
    at Layer.handle [as handle_request] (/home/samuel/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/samuel/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/samuel/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/samuel/node_modules/express/lib/router/layer.js:95:5)
    at /home/samuel/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/samuel/node_modules/express/lib/router/index.js:335:12)
    at next (/home/samuel/node_modules/express/lib/router/index.js:275:10)
    at serveStatic (/home/samuel/node_modules/serve-static/index.js:75:16)

**Comment by MeetPing** [comment]
@richardgirges

**Comment by RomanBurunkov** [comment]
Hi @MeetPing could you ellaborate your issue.
That looks like an error in your code.

**Comment by LucasPenen** [comment]
Same way here!
If I only put the basic example:

> const express = require('express');
const fileUpload = require('express-fileupload');
const app = express();

const PORT = 3000;
app.use('/form', express.static(__dirname + '/index.html'));

// default options
app.use(fileUpload());

app.get('/ping', function(req, res) {
  res.send('pong');
});

app.post('/upload', function(req, res) {
  let sampleFile;
  let uploadPath;

  if (Object.keys(req.files).length == 0) {
    res.status(400).send('No files were uploaded.');
    return;
  }

  console.log('req.files >>>', req.files); // eslint-disable-line

  sampleFile = req.files.sampleFile;

  uploadPath = __dirname + '/uploads/' + sampleFile.name;

  sampleFile.mv(uploadPath, function(err) {
    if (err) {
      return res.status(500).send(err);
    }

    res.send('File uploaded to ' + uploadPath);
  });
});

app.listen(PORT, function() {
  console.log('Express server listening on port ', PORT); // eslint-disable-line
});

I have the same error:

> TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at C:\Users\Lucas Penen\Projects\TimeabuKG\app2.js:19:14
    at Layer.handle [as handle_request] (C:\Users\Lucas Penen\Projects\TimeabuKG\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\Lucas Penen\Projects\TimeabuKG\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\Lucas Penen\Projects\TimeabuKG\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\Lucas Penen\Projects\TimeabuKG\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\Lucas Penen\Projects\TimeabuKG\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Users\Lucas Penen\Projects\TimeabuKG\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\Lucas Penen\Projects\TimeabuKG\node_modules\express\lib\router\index.js:275:10)
    at C:\Users\Lucas Penen\Projects\TimeabuKG\node_modules\express-fileupload\lib\index.js:32:41

>

**Comment by RomanBurunkov** [comment]
> TypeError: Cannot convert undefined or null to object
> at Function.keys ()

According to the module source in case there is no attached files, req.files is null, so you need to check whether req.files object or not.

Quick Example:

```
if (req.files && Object.keys(req.files).length === 0) {
return res.status(400).send('No files were uploaded.');
}
```

**Comment by LucasPenen** [comment]
Thanks @RomanBurunkov but I sending a file with the following form (like the example) and that's not working.

> <div class="form">
				<form action="http://localhost:3000/upload" method="POST">
					<label for="nro_orden">Order number</label>
					<input type="text" id="nro_orden" name="nro_orden" class="input-line">
					<label for="token">Token</label>
					<input type="text" id="token" name="token" class="input-line">
					<label for="file">Upload File</label>
					<input type="file" id="file" name="entrega">
					<input type="submit" id="submit" value="Submit" style="margin-top: 10px;">
				</form>
			</div>
