### ISSUE TITLE
Getting issue after updating to 1.1.6-alpha.1

### ISSUE THREAD

**Issue by yatindratailor** [richardgirges/express-fileupload#160]
/project/server/node_modules/express-fileupload/lib/processMultipart.js:86
    debugLog(options, `New file opload ${field} -> ${name}, bytes: ${getFileSize()}`);
                                         ^

ReferenceError: field is not defined
    at Busboy.busboy.on (/var/www/html/malta_react/server/node_modules/express-fileupload/lib/processMultipart.js:86:42)
    at Busboy.emit (events.js:189:13)
    at Busboy.emit (/var/www/html/malta_react/server/node_modules/busboy/lib/main.js:38:33)
    at PartStream.<anonymous> (/var/www/html/malta_react/server/node_modules/busboy/lib/types/multipart.js:213:13)
    at PartStream.emit (events.js:189:13)
    at HeaderParser.<anonymous> (/var/www/html/malta_react/server/node_modules/dicer/lib/Dicer.js:51:16)
    at HeaderParser.emit (events.js:189:13)
    at HeaderParser._finish (/var/www/html/malta_react/server/node_modules/dicer/lib/HeaderParser.js:68:8)
    at SBMH.<anonymous> (/var/www/html/malta_react/server/node_modules/dicer/lib/HeaderParser.js:40:12)
    at SBMH.emit (events.js:189:13)

**Comment by RomanBurunkov** [comment]
Hi @yatindratailor ,

I've fixed that and published alpha.2.

**Comment by RomanBurunkov** [comment]
I believe that was fixed in alpha.2
