### ISSUE TITLE
TypeError: callback is not a function

### ISSUE THREAD

**Issue by kovirolik** [richardgirges/express-fileupload#19]
\node_modules\express-fileupload\lib\index.js:66
                callback(null);
                ^

TypeError: callback is not a function
    at WriteStream.<anonymous> (\node_modules\express-fileupload\lib\index.js:66:17)
    at emitNone (events.js:91:20)
    at WriteStream.emit (events.js:185:7)
    at fs.js:2037:14
    at \node_modules\graceful-fs\graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:123:15)
[nodemon] app crashed - waiting for file changes before starting...
Is it express-fileupload related?

**Comment by nisan92** [comment]
Having same problem here 
node_modules/express-fileupload/lib/index.js:145
                callback(error);
                ^

TypeError: callback is not a function
    at doMove (/home/ubuntu/workspace/node_modules/express-fileupload/lib/index.js:145:17)
    at WriteStream.<anonymous> (/home/ubuntu/workspace/node_modules/express-fileupload/lib/index.js:168:15)
    at emitOne (events.js:101:20)
    at WriteStream.emit (events.js:188:7)
    at /home/ubuntu/workspace/node_modules/graceful-fs/graceful-fs.js:211:14
    at /home/ubuntu/workspace/node_modules/graceful-fs/graceful-fs.js:241:16
    at FSReqWrap.oncomplete (fs.js:123:15)
